version: '3.9'

services:
  app:
    image: snipe/snipe-it:latest
    container_name: app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      # SNIPE-IT
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_ENV=${APP_ENV}
      - APP_URL="http://${HOST_IP}:${HOST_HTTP_PORT}"
      - APP_TIMEZONE=${APP_TIMEZONE}
      - APP_LOCALE=${APP_LOCALE}
      # DB
      - MYSQL_PORT_3306_TCP_PORT=${DB_PORT}
      - MYSQL_PORT_3306_TCP_ADDR=${DB_HOSTNAME}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD={DB_PWD}
      # EMAILS
      - MAIL_PORT_587_TCP_ADDR=${MAIL_SRV}
      - MAIL_PORT_587_TCP_PORT=${MAIL_PORT}
      - MAIL_ENV_FROM_ADDR=${MAIL_ADDR}
      - MAIL_ENV_FROM_NAME=${MAIL_ALIAS}
      - MAIL_ENV_ENCRYPTION=${MAIL_ENCRY}
      - MAIL_ENV_USERNAME=${MAIL_USER}
      - MAIL_ENV_PASSWORD=${MAIL_PWD}
    ports:
      - ${HOST_IP}:${HOST_HTTP_PORT}:80
      # - ${HOST_IP}:${HOST_HTTPS_PORT}:443
    networks:
      - app_network
    healthcheck:
      test: "curl --fail http://localhost || exit 1"
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  db:
    image: mariadb:latest
    container_name: db
    restart: unless-stopped
    volumes:
      - .docker/db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - snipeitdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD={DB_PWD}
    networks:
      - app_network
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -uroot -p${DB_ROOT_PWD} || exit 1"
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  snipeitdata:

networks:
  app_network:
    driver: bridge
