version: '3.9'

services:
  app:
    build:
      context: .docker/apache
    container_name: app
    restart: unless-stopped
    volumes:
      - ./snipe-it:/var/www/html
    ports:
      - ${HOST_IP}:${HOST_HTTP_PORT}:80
      - ${HOST_IP}:${HOST_HTTPS_PORT}:443

  db:
    image: mariadb:latest
    container_name: db
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - ${HOST_IP}:${HOST_DB_PORT}:3306
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PWD}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PWD}

volumes:
  dbdata:

networks:
  app_network:
    driver: bridged
